server:
  port: 8083

spring:
  application:
    name: catalog-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:sqlserver://10.3.45.15:1433;databaseName=cms_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: root$123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    root: INFO
    com.nisum.catalog: INFO
    com.nisum.catalog.controller: DEBUG
    com.nisum.catalog.service: DEBUG
    # Silence noisy framework logs
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.cloud.netflix.eureka: WARN
    # ELIMINATE HIKARIPOLL NOISE
    com.zaxxer.hikari: ERROR
    com.zaxxer.hikari.HikariDataSource: ERROR
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari.pool: ERROR
    # Silence other noisy components
    org.springframework.jpa: WARN
    org.springframework.orm: WARN
    org.springframework.data: WARN
    org.springframework.boot.autoconfigure: WARN
    org.apache.tomcat: WARN
    org.apache.catalina: WARN

jwt:
  secret: mySecretJWTKey123456789012345678

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
