server:
    port: 8000

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                # User Service
                - id: user-service
                  uri: http://localhost:8084
                  predicates:
                    - Path=/user/**, /api/auth/**, /test/**
                # Product Management Service
                - id: product-management-service
                  uri: http://localhost:8081
                  predicates:
                    - Path=/sellers/**, /products/**, /categories/**
                # Inventory Service
                - id: inventory-service
                  uri: http://localhost:8082
                  predicates:
                    - Path=/api/orders/**, /api/inventory/**, /api/public/login
                # Catalog Service
                - id: catalog-service
                  uri: http://localhost:8083
                  predicates:
                    - Path=/api/promos/**, /api/product-categories/**, /api/promo-product-joins/**, /api/auth/**, /products/**
                # Cart and Checkout Service
                - id: cart-checkout-service
                  uri: http://localhost:8085
                  predicates:
                    - Path=/api/cart/**, /api/order/**, /api/checkout/**, /api/bill/**, /api/checkout-promo/**
                # Order Service
                - id: order-service
                  uri: http://localhost:8086
                  predicates:
                    - Path=/orders/**, /api/public/login, /admin/**, /shipment/**


eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        hostname: localhost

# Comprehensive Logging Configuration
logging:
    level:
        root: INFO
        com.nisum.apigateway: INFO
        com.nisum.apigateway.config: DEBUG
        org.springframework.cloud.gateway: INFO
        org.springframework.cloud.netflix.eureka: WARN
        # Silence noisy framework components
        org.springframework.web: WARN
        org.springframework.security: WARN
        reactor.netty: WARN
        io.netty: WARN
        org.springframework.boot.autoconfigure: WARN
        org.apache.catalina: WARN
        # ELIMINATE HIKARIPOLL NOISE (if any)
        com.zaxxer.hikari: ERROR
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file:
        name: logs/api-gateway.log
        max-size: 10MB
        max-history: 30
    logback:
        rollingpolicy:
            max-file-size: 10MB
            total-size-cap: 1GB

# Swagger/OpenAPI Configuration for API Gateway
springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls:
            - name: User Service
              url: /v3/api-docs/user-service
            - name: Product Management Service
              url: /v3/api-docs/product-management-service
            - name: Inventory Service
              url: /v3/api-docs/inventory-service
            - name: Cart and Checkout Service
              url: /v3/api-docs/cart-checkout-service
            - name: Order Service
              url: /v3/api-docs/order-service
            - name: Catalog Service
              url: /v3/api-docs/catalog-service
