# DevTools Configuration for Enhanced Development Experience
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      additional-exclude: static/**,public/**
      poll-interval: 1s
      quiet-period: 400ms
    livereload:
      enabled: true
      port: 35729
    add-properties: true
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  mustache:
    cache: false
  web:
    resources:
      cache:
        period: 0

