server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:sqlserver://10.3.45.15:1433;databaseName=snb_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: root$123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    root: INFO
    com.nisum.UserService: INFO
    com.nisum.UserService.controller: DEBUG
    com.nisum.UserService.service: DEBUG
    com.nisum.UserService.security: INFO
    # Silence noisy framework logs
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.cloud.netflix.eureka: WARN
    # ELIMINATE HIKARIPOLL NOISE
    com.zaxxer.hikari: ERROR
    com.zaxxer.hikari.HikariDataSource: ERROR
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari.pool: ERROR
    # Silence other noisy components
    org.springframework.jpa: WARN
    org.springframework.orm: WARN
    org.springframework.data: WARN
    org.springframework.boot.autoconfigure: WARN
    org.apache.tomcat: WARN
    org.apache.catalina: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 10MB
    max-history: 30
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
