server:
    port: 8000

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: user-service-user
                  uri: lb://user-service
                  predicates:
                      - Path=/user/**

                - id: user-service-test
                  uri: lb://user-service
                  predicates:
                      - Path=/test/**

                - id: category-service
                  uri: lb://product-management-service
                  predicates:
                      - Path=/categories/**

                - id: product-service-products
                  uri: lb://product-management-service
                  predicates:
                      - Path=/products/**

                - id: product-service-sellers
                  uri: lb://product-management-service
                  predicates:
                      - Path=/sellers/**

                # Catalog Service Routes (for promotions)
                - id: catalog-service-promos
                  uri: lb://catalog-service
                  predicates:
                      - Path=/api/promos/**

                - id: catalog-service-product-categories
                  uri: lb://catalog-service
                  predicates:
                      - Path=/api/product-categories/**

                - id: catalog-service-promo-product-joins
                  uri: lb://catalog-service
                  predicates:
                      - Path=/api/promo-product-joins/**

                - id: catalog-service-auth
                  uri: lb://catalog-service
                  predicates:
                      - Path=/api/auth/**

                # Inventory Service Routes
                - id: inventory-service-api-inventory
                  uri: lb://inventory-service
                  predicates:
                      - Path=/api/inventory/**

                - id: inventory-service-api-orders
                  uri: lb://inventory-service
                  predicates:
                      - Path=/api/orders/**

                - id: inventory-service-legacy
                  uri: lb://inventory-service
                  predicates:
                      - Path=/inventory/**

                - id: inventory-service-items
                  uri: lb://inventory-service
                  predicates:
                      - Path=/items/**

                # Cart & Checkout Service Routes - Complete configuration
                - id: cart-service-cart
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/api/cart/**

                - id: cart-service-order
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/api/order/**

                - id: cart-service-checkout
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/api/checkout/**

                - id: cart-service-bill
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/api/bill/**

                # Legacy checkout route (keeping for backward compatibility)
                - id: cart-checkout-service-checkout-legacy
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/checkout/**

                # Order Service Routes
                - id: order-service-orders
                  uri: lb://sprint4
                  predicates:
                      - Path=/orders/**

                - id: order-service-admin
                  uri: lb://sprint4
                  predicates:
                      - Path=/admin/**

                - id: order-service-shipment
                  uri: lb://sprint4
                  predicates:
                      - Path=/shipment/**

                - id: order-service-public
                  uri: lb://sprint4
                  predicates:
                      - Path=/api/public/**

                # Swagger Documentation Routes
                - id: user-service-swagger
                  uri: lb://user-service
                  predicates:
                      - Path=/v3/api-docs/user-service
                  filters:
                      - RewritePath=/v3/api-docs/user-service, /v3/api-docs

                - id: product-service-swagger
                  uri: lb://product-management-service
                  predicates:
                      - Path=/v3/api-docs/product-management-service
                  filters:
                      - RewritePath=/v3/api-docs/product-management-service, /v3/api-docs

                - id: inventory-service-swagger
                  uri: lb://inventory-service
                  predicates:
                      - Path=/v3/api-docs/inventory-service
                  filters:
                      - RewritePath=/v3/api-docs/inventory-service, /v3/api-docs

                - id: cart-checkout-service-swagger
                  uri: lb://cart-and-checkout-service
                  predicates:
                      - Path=/v3/api-docs/cart-checkout-service
                  filters:
                      - RewritePath=/v3/api-docs/cart-checkout-service, /v3/api-docs

                - id: order-service-swagger
                  uri: lb://sprint4
                  predicates:
                      - Path=/v3/api-docs/sprint4
                  filters:
                      - RewritePath=/v3/api-docs/sprint4, /v3/api-docs

                - id: catalog-service-swagger
                  uri: lb://catalog-service
                  predicates:
                      - Path=/v3/api-docs/catalog-service
                  filters:
                      - RewritePath=/v3/api-docs/catalog-service, /v3/api-docs

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        hostname: localhost

# Comprehensive Logging Configuration
logging:
    level:
        root: INFO
        com.nisum.apigateway: INFO
        com.nisum.apigateway.config: DEBUG
        org.springframework.cloud.gateway: INFO
        org.springframework.cloud.netflix.eureka: WARN
        # Silence noisy framework components
        org.springframework.web: WARN
        org.springframework.security: WARN
        reactor.netty: WARN
        io.netty: WARN
        org.springframework.boot.autoconfigure: WARN
        org.apache.catalina: WARN
        # ELIMINATE HIKARIPOLL NOISE (if any)
        com.zaxxer.hikari: ERROR
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file:
        name: logs/api-gateway.log
        max-size: 10MB
        max-history: 30
    logback:
        rollingpolicy:
            max-file-size: 10MB
            total-size-cap: 1GB

# Swagger/OpenAPI Configuration for API Gateway
springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls:
            - name: User Service
              url: /v3/api-docs/user-service
            - name: Product Management Service
              url: /v3/api-docs/product-management-service
            - name: Inventory Service
              url: /v3/api-docs/inventory-service
            - name: Cart and Checkout Service
              url: /v3/api-docs/cart-checkout-service
            - name: Order Service
              url: /v3/api-docs/sprint4
            - name: Catalog Service
              url: /v3/api-docs/catalog-service
