server:
  port: 8085

spring:
  application:
    name: cart-and-checkout-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cart_and_checkout_db;encrypt=true;trustServerCertificate=true;
    username: "sa"
    password: "Welcome@2026"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
